package LevelFour;
/*
 * https://leetcode.com/problems/find-the-difference/
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class FindTheDifference {

	public static char findTheDifference(String s, String t) {
		int[] charCount = new int[26];

		for (int i = 0; i < s.length(); i++) {
			char ch = s.charAt(i);
			charCount[ch - 'a']++;
		}
		char result = 'a';

		for (int i = 0; i < t.length(); i++) {
			char ch = t.charAt(i);
			charCount[ch - 'a']--;
			if (charCount[ch - 'a'] < 0) {
				result = ch;
				break;
			}
		}

		return result;
	}
	
	public static void main(String[] args) {		
		System.out.println(findTheDifference("abcd", "abcde"));//ans e.
	}

}
