package LevelFour;
/*
 * https://leetcode.com/problems/find-the-difference/
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class FindTheDifference {

	public static char findTheDifference(String s, String t) {
		int[] count = new int[26];
        char result = 'a';
        for(int i =0; i < s.length(); i++){
            count[s.charAt(i) - 'a']++;
        }
        
        for(int i =0; i < t.length(); i++){
            count[t.charAt(i) - 'a']--;
            if(count[t.charAt(i) - 'a'] < 0){
                result =  t.charAt(i);
            }
        }
        
        return result;
    }
	
	public static void main(String[] args) {		
		System.out.println(findTheDifference("abcd", "abcde"));//ans e.
	}

}
